#!/bin/sh
sudo DEBIAN_FRONTEND=noninteractive apt update -y && sudo apt upgrade -y
sudo DEBIAN_FRONTEND=noninteractive apt install -y git hostapd dnsmasq netfilter-persistent iptables-persistent
sudo systemctl stop hostapd dnsmasq
echo <<EOF > /tmp/dhcpcd.conf
interface wlan1
static ip_address=192.168.4.1/24
denyinterfaces eth1
EOF
sudo cp /tmp/dhcpcd.conf /etc/

cat <<EOF > /tmp/dnsmasq.conf
listen-address=::1,127.0.0.1,192.168.4.1,192.168.4.2
interface=eth0
interface=wlan1
domain=racetiming.lan
dhcp-range=192.168.4.101,192.168.4.200,255.255.255.0,24h
dhcp-leasefile=/var/lib/dnsmasq.leases
EOF
sudo cp /tmp/dnsmasq.conf /etc/

cat <<EOF > /tmp/hostapd.conf
interface=wlan1
bridge=br0
hw_mode=g
channel=7
wmm_enabled=0
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
ssid=racetiming
wpa_passphrase=racetiming
EOF
sudo mkdir -p /etc/hostapd/

sudo cp /tmp/hostapd.conf /etc/hostapd
sudo sh -c "echo DAEMON_CONF=\\\"/etc/hostapd/hostapd.conf\\\" >> /etc/default/hostapd"

cat <<EOF > /tmp/routed-ap.conf
net.ipv4.ip_forward=1
EOF
sudo cp /tmp/routed-ap.conf /etc/sysctl.d/

sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
sudo netfilter-persistent save
#sudo sh -c "iptables-save > /etc/iptables.ipv4.nat"
#sudo sh -c "echo iptables-restore \< /etc/iptables.ipv4.nat >> /etc/rc.local"
#sudo brctl addbr br0
#sudo brctl addif br0 eth0
#sudo brctl addif br0 eth1

cat <<EOF > /tmp/eth0
auto eth0
iface eth0 inet static
    address 192.168.4.2
    network 192.168.4.0
    netmask 255.255.255.0
EOF
sudo cp /tmp/eth0 /etc/network/interfaces.d/

cat <<EOF > /tmp/eth1
auto eth1
interface eth1 inet dhcp
EOF
sudo cp /tmp/eth1 /etc/network/interfaces.d/

cat <<EOF > /tmp/wlan1
auto wlan1
iface wlan1 inet static
    address 192.168.4.1
    network 192.168.4.0
    netmask 255.255.255.0
    nohook wpa_supplicant
EOF
sudo cp /tmp/wlan1 /etc/network/interfaces.d/

#cat <<EOF > /tmp/br0
#auto br0
#iface br0 inet manual
#bridge_ports eth0 eth1 wlan1
#EOF
#sudo cp /tmp/br0 /etc/network/interfaces.d/
